CREATE TABLE `user` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(150) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`email` VARCHAR(150) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`status` TINYINT(1) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `email` (`email`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
